spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database;DB_CLOSE_ON_EXIT=FALSE

  h2:
    console:
      enabled: true
      path: /h2-console

camunda:
  bpm:
    database:
      schema-update: true  # Auto-updates the database schema

camunda.bpm.admin-user:
  id: demo
  password: demo

server:
  port: 8066